<a href="https://colab.research.google.com/github/sada1908/edyoda_python/blob/main/edyoda_numpy_Assign02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# Create a null vector of size 10 but the fifth value which is 1.
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [3]:
x_vector = np.arange(10, 50)
print(x_vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [4]:
a_matrix = np.arange(0, 9).reshape(3, 3)
print(a_matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
y_vector = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(y_vector)
print(non_zero_indices)

(array([0, 1, 4]),)


In [7]:
b_array = np.random.random((10, 10))
b_min = np.min(b_array)
b_max = np.max(b_array)
print(b_min, b_max)

0.0011387914698335333 0.9926706930951381


In [8]:
random_vector = np.random.random(30)
mean_value = np.mean(random_vector)
print(mean_value)

0.6349687196184084
